name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'
        cache: 'npm'
    - name: Run npm install
      run: npm ci
    - name: Package
      run: npx vsce package
    - name: Delete release if exists
      run: gh release delete ${{ github.ref_name }} -y
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Create release
      run: gh release create ${{ github.ref_name }} --generate-notes *.vsix
      env:
        GITHUB_TOKEN: ${{ github.token }}
